"""
INTEGRADOR Version Information
Generated by tools/build_release.py
"""

__version__ = "1.25.09.26"
__version_info__ = (1, 25, 9, 26)
__build__ = 25
__author__ = "RD Devices Team"
__date__ = "2026-09-01"

VERSION = __version__
BUILD_DATE = __date__
